name: Bug Report
description: Create a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - knoake
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: Triggering a download fails with a 404 error
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior.

        A unit test would be very helpful.

      placeholder: |
        ```typescript
        it('test downloadPhoto', function (done) {
          service
            .downloadPhoto({
              links: {
                download_location:
                  'https://api.unsplash.com/photos/LBI7cgq3pbM/download?ixid=MnwxMTc4ODl8MHwxfHNlYXJjaHwxfHxwdXBweXxlbnwwfHx8fDE2MTc3NTA2MTM',
              },
            } as Photo)
            .subscribe((result) => {
              expect(result).toBeTruthy();
              done();
            });

          const req = httpTestingController.expectOne(
            'https://example.com/photos/LBI7cgq3pbM/download?ixid=MnwxMTc4ODl8MHwxfHNlYXJjaHwxfHxwdXBweXxlbnwwfHx8fDE2MTc3NTA2MTM'
          );
          expect(req.request.method).toEqual('GET');
          expect(req.request.headers.get('Authorization')).toEqual('Bearer 123');

          req.flush({});
        });
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: The download is successful with a 200 response status code
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens.
      placeholder: The download fails with a 404 response status code
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notes
      description: |
        Any additional information that might be useful

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
